module(load="imfile")

# Input A: explicit file from custom ulogd config
input(
    type="imfile"
    File="/var/log/ulog/iptables_ulogd2.log"
    Tag="ulog"
    Ruleset="ulog-rules"
)

# Input B: fallback default file if ulogd default config is used
input(
    type="imfile"
    File="/var/log/ulog/syslogemu.log"
    Tag="ulog"
    Ruleset="ulog-rules"
)

ruleset(name="ulog-rules") {
    if ($msg contains "RULE=") then {
        action(
            type="omfwd"
            target="__SYSLOG_NG_IP__"
            port="514"
            protocol="tcp"
            action.resumeRetryCount="-1"
            queue.type="linkedList"
            queue.size="10000"
        )

        action(type="omfile" file="/var/log/opsie.log")
        stop
    }
}

