input {
  tcp {
    port => 5044
    codec => json_lines
  }
}

filter {
  if ![datetime] and [@timestamp] {
    mutate { add_field => { "datetime" => "%{@timestamp}" } }
  }

  mutate {
    uppercase => ["proto"]
    gsub => [
      "action", "^PERMIT$", "Permit",
      "action", "^DENY$", "Deny"
    ]
  }

  if ![policyid] {
    mutate { add_field => { "policyid" => "999" } }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "opsie-firewall-%{+YYYY.MM.dd}"
  }
  stdout { codec => rubydebug }
}

